pipelines:
  - name: affinity_pipeline
    setup:
      runtime: onHost
    steps:
      - name: step1
        type: bash
        configuration:
          affinityGroup: test_group123
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7
                tag: $IMAGE_TAG
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
      - name: step2
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7
                tag: $IMAGE_TAG
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step1
      - name: step3
        type: bash
        configuration:
          affinityGroup: group2
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7
                tag: $IMAGE_TAG
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step2
      - name: step4
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7
                tag: $IMAGE_TAG
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step1
      - name: step5
        type: bash
        configuration:
          affinityGroup: group2
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7
                tag: $IMAGE_TAG
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step2
  - name: affinity_pipeline2
    setup:
      runtime: onHost
    steps:
      - name: step2_1
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7
                tag: $IMAGE_TAG
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
      - name: step2_2
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step2_1
      - name: step2_3
        type: bash
        setup:
          environmentVariables:
            normal:
              foo: bar
              boo: $foo
              shoo: foo boo
              moo: '"abc def"'
              zoo: '"\$a$foo"'
              koo: \(\)\$\\\!\@#%^*
              IMAGE_TAG: v7.2.4
          runtime:
            type: image
            image:
              custom:
                name: drydock/c7
                tag: $IMAGE_TAG
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step2_2
      - name: step2_4
        type: bash
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_chaitanya
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step2_2
